### ISSUE TITLE
Testing a TODO

### ISSUE THREAD

**Issue by sanand0** [sanand0/sanand0.github.io#1]
Can I create things I learned notes and TODOs as GitHub issues easily enough? Testing...

- [x] Task lists are easy
- [ ] ... But not that well formatted on mobile app
- [ ] You can't create a new label
- [ ] But you can add images, code

![IMG-20240909-WA0009.jpg](https://github.com/user-attachments/assets/6030186a-2412-42e1-96b6-8ea2acc24b32)

```
Some code here 
```
